version: '3'
services:
  db:
    image: postgres:13.15-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: notes
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    stdin_open: true
    tty: true # Enables debugging capabilities when attached to this container.
    build: .
    user: "1000:1000"
    environment:
      RAILS_ENV: development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db